### ISSUE TITLE
Request: adding proxy variables build args for external dependencies

### ISSUE THREAD

**Issue by dRy3vd** [unfetter-discover/unfetter#1172]
When a container build pulls in external dependencies (e.g.: npm), the build breaks if your connection is forced through a proxy.  To resolve, one has to pass in proxy variables for each image that has external dependencies in one of the following manners (with the compose files):

`env_file: .env`

where the .env has http_proxy, https_proxy, no_proxy defined.

or 
```
     build:
       context: ./web
       args:
          http_proxy: $http_proxy
          https_proxy: $https_proxy
```

Is there a way to support this in future compose files without manually editing/merging or perhaps support within ansible?
